module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  automated_cron: 0
  block: 0
  breakpoint: 0
  config: 0
  config_readonly: 0
  config_translation: 0
  content_entity_base: 0
  contextual: 0
  csv_serialization: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  entity: 0
  entity_reference_revisions: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  flysystem: 0
  flysystem_dropbox: 0
  geolocation: 0
  help: 0
  image: 0
  inline_form_errors: 0
  language: 0
  link: 0
  locale: 0
  media_entity: 0
  media_entity_image: 0
  menu_ui: 0
  migrate: 0
  migrate_plus: 0
  migrate_source_csv: 0
  migrate_tools: 0
  nica_custom: 0
  nica_entity: 0
  nica_migrate: 0
  node: 0
  options: 0
  page_cache: 0
  paragraphs: 0
  rest: 0
  serialization: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  text: 0
  toolbar: 0
  twig_tweak: 0
  update: 0
  user: 0
  views_rest_feed: 0
  views_ui: 0
  menu_link_content: 1
  views: 10
  config_installer: 1000
theme:
  classy: 0
  bartik: 0
  seven: 0
  stable: 0
  bootstrap: 0
  nica_theme: 0
  adminimal_theme: 0
  nica_admin: 0
langcode: es
