cdn_provider: ''
_core:
  default_config_hash: _5qrDuRmWmRVjW00si3U1s1NrgrocA4N653EYGRfgEE
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://nica.dev/themes/custom/nica_theme/favicon.ico'
  use_default: true
schema: '8000'
navbar_inverse: 1
navbar_position: fixed-top
cdn_provider_import_data: ''
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: ''
  url: ''
  use_default: true
schemas:
  bootstrap: 8000
  nica_theme: 8000
